- lecture10/estimation_identification.jmd
> missing mathbb in lecture 10

- lecture4/dynamical_systems.jmd
I think there's a mistake here.
> Fix "Update Form" session

- lecture7/discretizing_odes.jmd
The html file was not re-weaved however.
> fix to RK4 latex in lecture 7 

- lecture11/adjoints.jmd
> typo in Lecture 11

- lecture3/sciml.jmd
Fixed a couple of simple typos. Also corrected a small math error to set $g(0) = u_0$ instead of $g(0) = 0$.
> fixed a few typos.

- _weave/lecture08/automatic_differentiation.jmd
Fixes https://github.com/SciML/SciMLBook/issues/40
> Update function definitions in forward-mode AD lectures

- _weave/lecture07/discretizing_odes.jmd
A native speaker should check if the corrections are correct.
> Some typos and one equation corrected

- _weave/lecture10/estimation_identification.jmd
Given... A baby step in open source contribution :)
> Fixed case on one letter

- _css/franklin.css
- config.md
- index.md
In response to #58 
Reduce friction to getting feedback on course material and site suggestions.
> Add links to homepage to create new issues (#58)

- _weave/homework02/hw2.jmd
- _weave/homework03/hw3.jmd
- _weave/lecture02/optimizing.jmd
- _weave/lecture03/sciml.jmd
- _weave/lecture04/dynamical_systems.jmd
- _weave/lecture05/parallelism_overview.jmd
- _weave/lecture06/styles_of_parallelism.jmd
- _weave/lecture07/discretizing_odes.jmd
- _weave/lecture08/automatic_differentiation.jmd
- _weave/lecture09/stiff_odes.jmd
- _weave/lecture10/estimation_identification.jmd
- _weave/lecture11/adjoints.jmd
- _weave/lecture13/gpus.jmd
- _weave/lecture14/pdes_and_convolutions.jmd
- _weave/lecture15/diffeq_machine_learning.jmd
- _weave/lecture16/probabilistic_programming.jmd
- _weave/lecture17/global_sensitivity.jmd
- _weave/lecture19/uncertainty_programming.jmd
> Clean lectures and homeworks

- _layout/nav.html
> Fix broken link for lecture 8 notes

- _weave/lecture16/probabilistic_programming.html
change the typo error: Fix Typo: Chpt. 15, Hamiltonian MC
> change Fix Typo: Chpt. 15, Hamiltonian MC

- _weave/lecture03/sciml.html
not knowing what the original intended meaning was
> change exceptionally to exceptionally effective

- _weave/lecture11/adjoints.html
- _weave/lecture11/adjoints.jmd
fixed derivation mistake in note 11 #68
> Fixes #68 mistake in derivation

- _weave/lecture04/dynamical_systems.jmd
Missing $, so Latex formula isn't rendered
> Fix typo in dynamical_systems.jmd

- _weave/lecture11/adjoints.jmd
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
> minor typos in adjoints.jmd

- _weave/lecture16/probabilistic_programming.jmd
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
> minor typos

- _weave/lecture08/automatic_differentiation.jmd
Fixes https://github.com/SciML/SciMLBook/issues/133.
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
> Fix Struct of Arrays section

- _weave/lecture06/styles_of_parallelism.jmd
> Fix typo in lecture06

- _assets/scripts/js/back_to_top.js
- _css/adjust.css
- _css/franklin.css
- _css/tufte.css
- _layout/back_to_top.html
- _layout/foot.html
- _layout/page_foot.html
*(Not applicable — purely UI change, no testable logic added)*
*(UI only; no core API touched)*
*(Not applicable — no changes to docs needed; UI changes are self-explanatory or already covered)*
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
*(No new documentation added, but change is UI-only and public-facing)*
Implemented a "Back to Top" button to enhance user navigation by allowing users to quickly return to the top of the page after scrolling. Refactored the button’s logic for cleaner structure and improved maintainability. Also adjusted text alignment to be justified for better visual consistency across the UI.
> Add back-to-top button functionality and text justification
